-- ==============================================================================
-- 01_schema.sql
-- LexMed Forensic Medicine Department Database System
-- Schema Initialization and Refactoring
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. IAM and Core Base Entities
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS roles (
    role_id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS permissions (
    permission_id INT AUTO_INCREMENT PRIMARY KEY,
    permission_name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(permission_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    role_id INT NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    -- password_hash must be a bcrypt hash generated by the application (Phase 2)
    password_hash VARCHAR(255) NOT NULL,
    status ENUM('active', 'disabled') DEFAULT 'active',
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS user_sessions (
    session_id VARCHAR(36) PRIMARY KEY,
    user_id INT NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    log_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    action VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    record_id INT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

-- Index: Audit review always filters by a specific user within a date range.
CREATE INDEX idx_audit_logs_user_time ON audit_logs(user_id, timestamp);


CREATE TABLE IF NOT EXISTS forensic_cases (
    case_id INT AUTO_INCREMENT PRIMARY KEY,
    case_number VARCHAR(100) UNIQUE NOT NULL,
    -- Victim/patient identifying details are encrypted at the application layer.
    patient_nic_encrypted VARBINARY(255),
    patient_nic_hash VARCHAR(64),
    patient_name_encrypted VARBINARY(255),
    case_type ENUM('Clinical', 'Postmortem', 'Mixed') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ------------------------------------------------------------------------------
-- 2. Medical Entities and Lookup Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS legal_authorities (
    authority_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    designation VARCHAR(255),
    jurisdiction VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS hospital_wards (
    ward_id INT AUTO_INCREMENT PRIMARY KEY,
    ward_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ward_admissions (
    admission_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    ward_id INT NOT NULL,
    bht_number VARCHAR(255) NOT NULL,
    admit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT,
    FOREIGN KEY (ward_id) REFERENCES hospital_wards(ward_id) ON DELETE RESTRICT
);

-- Index: Used to track patient locations per case.
CREATE INDEX idx_ward_admissions_case_ward ON ward_admissions(case_id, ward_id);


-- ------------------------------------------------------------------------------
-- 3. Clinical Forensic Medicine (Module 4)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS clinical_exams (
    exam_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    jmo_id INT NOT NULL,
    consent_status VARCHAR(50) NOT NULL,
    history_given TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT,
    FOREIGN KEY (jmo_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    CONSTRAINT chk_consent_status CHECK (consent_status IN ('Given', 'Refused', 'Pending', 'Not Required'))
);

CREATE TABLE IF NOT EXISTS injury_records (
    injury_id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    injury_type VARCHAR(100) NOT NULL,
    weapon VARCHAR(255),
    body_part VARCHAR(255),
    hurt_category VARCHAR(100),
    FOREIGN KEY (exam_id) REFERENCES clinical_exams(exam_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS clinical_referrals (
    referral_id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    department VARCHAR(255) NOT NULL,
    referral_date DATE NOT NULL,
    findings TEXT,
    FOREIGN KEY (exam_id) REFERENCES clinical_exams(exam_id) ON DELETE RESTRICT
);


-- ------------------------------------------------------------------------------
-- 4. Postmortem (Module 5)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS postmortems (
    pm_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    jmo_id INT NOT NULL,
    death_category VARCHAR(100),
    pm_date TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT,
    FOREIGN KEY (jmo_id) REFERENCES users(user_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS causes_of_death (
    cod_id INT AUTO_INCREMENT PRIMARY KEY,
    pm_id INT NOT NULL,
    immediate_cause TEXT,
    antecedent_cause TEXT,
    contributory TEXT,
    UNIQUE (pm_id),
    FOREIGN KEY (pm_id) REFERENCES postmortems(pm_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS histology_samples (
    histology_id INT AUTO_INCREMENT PRIMARY KEY,
    pm_id INT NOT NULL,
    tissue_type VARCHAR(255) NOT NULL,
    analysis_result TEXT,
    FOREIGN KEY (pm_id) REFERENCES postmortems(pm_id) ON DELETE RESTRICT
);


-- ------------------------------------------------------------------------------
-- 5. Advanced Investigations (Module 6)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS radiology_scans (
    scan_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    modality VARCHAR(100) NOT NULL,
    body_region VARCHAR(255),
    findings TEXT,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS toxicology_tests (
    tox_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    sample_material VARCHAR(255) NOT NULL,
    substance_tested VARCHAR(255),
    result TEXT,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT
);


-- ------------------------------------------------------------------------------
-- 6. Law & Evidence (Module 7)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS legal_documents (
    doc_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    authority_id INT,
    doc_type VARCHAR(100) NOT NULL,
    reference_no VARCHAR(255),
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT,
    FOREIGN KEY (authority_id) REFERENCES legal_authorities(authority_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS evidence_items (
    item_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    item_type VARCHAR(100) NOT NULL,
    description TEXT,
    current_status VARCHAR(100),
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT,
    CONSTRAINT chk_evidence_status CHECK (current_status IN ('Available', 'In Transit', 'At Court', 'Disposed'))
);

-- Index: Looked up frequently when viewing a case's chain of custody.
CREATE INDEX idx_evidence_items_case ON evidence_items(case_id);


CREATE TABLE IF NOT EXISTS chain_of_custody (
    transfer_id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT NOT NULL,
    released_by_user INT,
    received_by_name VARCHAR(255) NOT NULL,
    transfer_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES evidence_items(item_id) ON DELETE RESTRICT,
    FOREIGN KEY (released_by_user) REFERENCES users(user_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS court_reports (
    report_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    report_type VARCHAR(100) NOT NULL,
    trial_date DATE,
    receipt_status BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS court_summons (
    summon_id INT AUTO_INCREMENT PRIMARY KEY,
    jmo_id INT NOT NULL,
    case_id INT NOT NULL,
    appearance_date DATE NOT NULL,
    status VARCHAR(50),
    FOREIGN KEY (jmo_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT,
    CONSTRAINT chk_summons_status CHECK (status IN ('Issued', 'Served', 'Attended', 'Dismissed'))
);

-- Index: Used for daily/weekly upcoming court schedules for JMOs.
CREATE INDEX idx_court_summons_date ON court_summons(appearance_date);


CREATE TABLE IF NOT EXISTS digital_media (
    media_id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    encrypted_url TEXT NOT NULL,
    upload_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES forensic_cases(case_id) ON DELETE RESTRICT
);
